[versions]
kotlin = "2.3.0"
oshai-logging = "7.0.7"
koog = "0.6.0"
versions = "0.53.0"

[libraries]
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
oshai-kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "oshai-logging" }


[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
